application:
  name: screening-service

tracer:
  host: ${TRACER_HOST:localhost}
  port: ${TRACER_PORT:6831}

spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/screening}
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka:9092}
    consumer:
      group-id: needLoanEvent-screening-consumer-group
      auto-offset-reset: earliest
      properties:
        interceptor:
          classes: io.opentracing.contrib.kafka.TracingConsumerInterceptor
    producer:
      properties:
        interceptor:
          classes: io.opentracing.contrib.kafka.TracingProducerInterceptor

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,info,health

server:
  port: 8084