spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/screening}
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka:9092}
    consumer:
      group-id: needLoanEvent-screening-consumer-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,info,health

server:
  port: 8084